# Generated by Django 4.0.1 on 2022-02-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='other', max_length=100, verbose_name='Категория'),
        ),
    ]
