# Generated by Django 4.0.1 on 2022-02-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='magazine_app.category', verbose_name='Категория'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='magazine_app_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='magazine_app_product',
        ),
    ]
