# Generated by Django 4.0.1 on 2022-02-08 15:02

from django.db import migrations, models
import django.db.models.deletion
import magazine_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, max_length=10, validators=[magazine_app.validators.MinValueValidator(0.01)], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remainder',
            field=models.IntegerField(blank=True, null=True, validators=[magazine_app.validators.MinValueValidator(0)], verbose_name='Остаток'),
        ),
        migrations.CreateModel(
            name='ProductInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[magazine_app.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='magazine_app.product', verbose_name='Товары в корзине')),
            ],
        ),
    ]
