# Generated by Django 4.0.1 on 2022-02-08 20:46

from django.db import migrations, models
import magazine_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0006_alter_productincart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='count',
            field=models.IntegerField(validators=[magazine_app.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
