# Generated by Django 4.0.1 on 2022-02-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine_app', '0009_cart_alter_orderproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='qty',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='magazine_app_orderproduct',
        ),
    ]
